const REQUEST_ADD_TO_CART = 'REQUEST_ADD_TO_CART';
const REQUEST_ADD_TO_CART_SUCCESS = 'REQUEST_ADD_TO_CART_SUCCESS';
const REQUEST_ADD_TO_CART_FAILURE = 'REQUEST_ADD_TO_CART_FAILURE';
const RECEIVE_MODS_DATA = 'RECEIVE_MOD_DATA';
const REQUEST_MODS_DATA = 'REQUEST_MOD_DATA';
const REQUEST_MODS_DATA_FAILURE = 'REQUEST_MOD_DATA_FAILURE';
const ADD_TO_SEEN = 'ADD_TO_SEEN';
const ADD_TO_CLICKED = 'ADD_TO_CLICKED';

export default {
    ADD_TO_CLICKED,
    ADD_TO_SEEN,
    REQUEST_ADD_TO_CART,
    REQUEST_ADD_TO_CART_SUCCESS,
    REQUEST_ADD_TO_CART_FAILURE,
    RECEIVE_MODS_DATA,
    REQUEST_MODS_DATA,
    REQUEST_MODS_DATA_FAILURE,
}
