const TEST = 'TEST';
const FETCHDATA = 'FETCHDATA';
const RECEIVE_MODS_DATA = 'RECEIVE_MODS_DATA';
const REQUEST_MODS_DATA = 'REQUEST_MODS_DATA';
const REQUEST_MODS_DATA_FAILURE = 'REQUEST_MODS_DATA_FAILURE';
const RECEIVE_NEXT_MODS_DATA = 'RECEIVE_NEXT_MODS_DATA';
const REQUEST_NEXT_MODS_DATA = 'REQUEST_NEXT_MODS_DATA';
const REQUEST_NEXT_MODS_DATA_FAILURE = 'REQUEST_NEXT_MODS_DATA_FAILURE';

export default {
    TEST,
    FETCHDATA,
    RECEIVE_MODS_DATA,
    REQUEST_MODS_DATA,
    REQUEST_MODS_DATA_FAILURE,
    RECEIVE_NEXT_MODS_DATA,
    REQUEST_NEXT_MODS_DATA,
    REQUEST_NEXT_MODS_DATA_FAILURE
}