const RECEIVE_MEDIA_ITEM = 'RECEIVE_MEDIA_ITEM'
const REQUEST_MEDIA_ITEM = 'REQUEST_MEDIA_ITEM'
const REQUEST_MEDIA_ITEM_FAILURE = 'REQUEST_MEDIA_ITEM_FAILURE'
const RECEIVE_SIMILAR_ROOMS = 'RECEIVE_SIMILAR_ROOMS'
const REQUEST_SIMILAR_ROOMS = 'REQUEST_SIMILAR_ROOMS'
const REQUEST_SIMILAR_ROOMS_FAILURE = 'REQUEST_SIMILAR_ROOMS_FAILURE'
const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS'
const REQUEST_PRODUCTS_FAILURE = 'REQUEST_PRODUCTS_FAILURE'

export default {
    RECEIVE_MEDIA_ITEM,
    REQUEST_MEDIA_ITEM,
    REQUEST_MEDIA_ITEM_FAILURE,
    RECEIVE_SIMILAR_ROOMS,
    REQUEST_SIMILAR_ROOMS_FAILURE,
    REQUEST_SIMILAR_ROOMS,
    RECEIVE_PRODUCTS,
    REQUEST_PRODUCTS_FAILURE,
    REQUEST_PRODUCTS
}

